version: "3.7"

services:

  secator:
    image: freelabz/secator
    restart: unless-stopped
    entrypoint: ""
    command: tail -F anything
    environment:
    - SECATOR_CELERY_BROKER_URL=redis://redis:6379/0
    - SECATOR_CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: unless-stopped
    command: worker
    environment:
    - SECATOR_CELERY_BROKER_URL=redis://redis:6379/0
    - SECATOR_CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:latest
